name: Workflow de secrets

on:
  workflow_dispatch

jobs:
    print-secrets:
      runs-on: ubuntu-latest
      steps:
      - name: Tentando expor secret
        run: echo "${{ secrets.minha_secret }}"
        
      - name: Tentando expor secret com saída manipulada
        run: echo "${{ secrets.minha_secret }}" | sed 's/./& /g'