name: Publicacao

on:
  workflow_run:
    workflows: ["build-e-testes"]
    types:
      - completed

jobs:
  publicar:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Publicar
        run: echo "App publicado"